### ISSUE TITLE
[suggestion]Todo progress instead of completion

### ISSUE THREAD

**Issue by greenSnot** [ultralist/ultralist#103]
```
all
1  [40%] asdfasdf
2 [100%] asdfasdf
```

**Comment by stuartskelton** [comment]
I can see this working for projects which can contain multiple todos items, but not for a single todo item as they should be a (imvho) binary in their completed status.

**Comment by gammons** [comment]
@stuartskelton exactly.  I'm envisioning this as the project or context shows the % complete, next to the name.  It could be a good enhancement!

**Comment by gammons** [comment]
closing in favor of #194
