### ISSUE TITLE
number and checkbox spacing

### ISSUE THREAD

**Issue by sheim** [ultralist/ultralist#123]
Hi, I'm quite enjoying todolist sofar. I sometimes find it a bit difficult to identify the number of a task (which number corresponds to which description). I think part of the issue is that I have most tasks (so far) without due dates, and therefore there is quite a lot of empty space between the number/checkbox and the description.  

I think it would help a lot if the due date was moved to be the leftmost column, with the number/checkbox in the middle and immediately to the left of the description.  

Another idea would be to have alternate-colored lines, but that would imho be a bit more complicated to get to mesh well with the custom settings people might have for their terminal colors.

**Comment by gammons** [comment]
@sheim thanks for the comment!  I'm still having trouble seeing how that would work if we switched the date and checkbox columns.  there's definitely some formatting issues, regardless.

**Comment by gammons** [comment]
I believe #133 will fix this.
