### ISSUE TITLE
Incorrect spacing/styling for prioritised notes

### ISSUE THREAD

**Issue by MalcolmK** [ultralist/ultralist#125]
When a note is prioritised and the note id is higher than 9, the spacing is a bit messy, see screenshot below:

![image](https://user-images.githubusercontent.com/2427717/37759444-ef0c1dee-2db3-11e8-8c1d-3fd61499a515.png)

I'm on a Mac and I am using v0.8

**Comment by gammons** [comment]
this is a stale issue and is likely fixed with the new screen formatter.
