### ISSUE TITLE
the future of todolist

### ISSUE THREAD

**Issue by gammons** [ultralist/ultralist#136]
Hey all, I wanted to let you know that I have some pretty big plans for todolist.  Below are what I was thinking:

1. **Rename todolist to ultralist**.  It was a mistake to name this tool in such a generic way.  I think it's hindered it's growth / adoption.  `ultralist` is more unique and memorable.  I also purchased `ultralist.io`.

2. **Create a service that allows syncing todo lists** between different computers.  Although Dropbox works pretty well, it doesn't handle conflicts amazingly.   In addition, the service would also have the following:

* A hosted web view of your synced todolists
* An Android + IOS version as well

The service would be a paid service, something super cheap (like $3/month).  My ultimate aspirations are to turn it from a side project into something that could support me and my family.  It would compete with Wunderlist, et al, but would continue to have a far superior command-line experience.

Also, it's important to note - the CLI version of `ultralist` (this current project) would *stay open source*, and would continue to be maintained + have sensible features built on top of it.

What do y'all think about this plan?  Does it make sense?  Would you be interested in a service like the above, if I built it?

ping @stuartskelton @ingorichter

**Comment by gammons** [comment]
hey, I did this!

**Comment by ipstone** [comment]
Hey Gammons, I just enjoyed todolist - agree that changing to a non-generic name is a good idea. 
However, as an command line utility - somehow tying it with a paid model gives me strange feeling - as in general, people are looking for open source utility in the hope of not locking in ... I wouldn't mind
