### ISSUE TITLE
No windows build, and problems compiling on windows

### ISSUE THREAD

**Issue by matjojo** [ultralist/ultralist#154]
Before noticing the windows build on the last version of TodoList I was trying to compile the ultralist package from source and ran into several problems. I tried to check issues for people with similar problems and found #146 . That pointed me towards the older versions that did have a windows executable.

For now I've installed that older version, but would of course love to get a never version as soon as possible. 
The compiling problems mostly had to do with incorrect imports and some variables not being set whilst compiling. It could be that this is just an issue in the newest code and not in one of the releases, so I'll hold off on trying to compile again to get the traces untill I know that I'm not just bothering you with old news

**Comment by gammons** [comment]
Hi @matjojo yep, I know.  this is on my list to fix.

**Comment by gammons** [comment]
This issue is here https://github.com/ultralist/ultralist/blob/master/ultralist/synchronizer.go#L42

Basically, I don't think windows supports `Setpgid` and therefore we won't be able to do background syncs to ultralist.io on windows.

**Comment by matjojo** [comment]
Hmmm, would it be possible to just not use that functionality in windows? Or is the code so intertwined that it would be hard to uncouple?

Also I don't  see an option to necro old issues but #69 is also hurting me. Will post more info there

**Comment by gammons** [comment]
@matjojo I think I found a platform-agnostic way of doing background sync, and created #155 .  Syncing works great in linux, so I'll cut a release today.
