### ISSUE TITLE
Move Priority tasks to top of respective lists

### ISSUE THREAD

**Issue by nlsdfnbch** [ultralist/ultralist#157]
Currently, when adding a priority flag to a task, they simply show up at the bottom of the list. I believe this to be counter-intuitive. Important todos should be at the top.

In order to implement this, a simple sort should be executed before displaying the todos.

This should also hold true when sorting by context or projects.

Current case:

```bash
$ ultralist a item-1
$ ultralist a item-2
$ ultralist a item-3
$ ultralist l

all
1        [  ]                   item-1
2        [  ]                   item-2
3        [  ]                   item-3
$ultralist p 2
$ultralist l

all
1        [  ]                   item-1
3        [  ]                   item-3
2[  ]                  item-2
```

desired output:

```bash
$ ultralist l

all
2        [  ]                   item-2
1        [  ]                   item-1
3        [  ]                   item-3
```

*Note*: This is also a great opportunity to fix priority task formatting.

**Comment by gammons** [comment]
agreed, and I already made a change to make prioritized todos at the top of groups for the ultralist.io UI.

**Comment by timorunge** [comment]
I'd also add todos with a due date on top of the list. Personally I'd prefer the following order:

- prioritised todos
- overdue todos
- due today
- some due date
- no due date
