### ISSUE TITLE
Use golint and gofmt in ultralist? 

### ISSUE THREAD

**Issue by timorunge** [ultralist/ultralist#160]
I think it would be great to align the coding style in ultralist with some common standards. Meaning to lint the code with [golint](https://github.com/golang/lint) and use [gofmt](https://golang.org/cmd/gofmt/) for formatting. 

@gammons WDYT?

**Comment by gammons** [comment]
@timorunge agreed.  I think we're pretty close.  If you want to submit a PR I'll get it merged.

**Comment by gammons** [comment]
#162
