### ISSUE TITLE
Several bugs on ultralist.io

### ISSUE THREAD

**Issue by timorunge** [ultralist/ultralist#161]
Can't send a PR since this is not on GH.

Quick list:

- Todos canwbe prioritized -> Todos can be prioritized
- Ultralist uses a simple .todos.json format for storing todos. -> Ultralist uses simple json for storing todos. 
- Mac OS: Run brew install ultralist. -> Mac OS: Run `brew install ultralist`.
- List your todo: `ultralist l to see the todo you added.` -> List your todo: `ultralist l` to see the todo you added.
- Github icon in the footer is pointing to https://github.com/ultralist/ultralis 

And:

- Ultralist is built for speed. It is written in Go.

Just because it's written in Go it's not meant to be fast. ;)

**Comment by gammons** [comment]
Hi @timorunge thanks for finding all those typos!  I updated the marketing site accordingly. 

Also, the marketing site _is_ on GH, I'm trying to keep everything as open as possible: https://github.com/ultralist/new-ultralist-marketing-site
