### ISSUE TITLE
if a todo has a priority, all todos show priority

### ISSUE THREAD

**Issue by gammons** [ultralist/ultralist#166]
![image](https://user-images.githubusercontent.com/38560/54491314-e8860380-4893-11e9-8f4e-046173b1ef49.png)

In this case, only todo 7 has the priority flag.  @timorunge I believe this is related to #159.  I have a feeling that `color.Add` is not resetting itself once we're done printing.

**Comment by timorunge** [comment]
@gammons I was taking a look at the code from `fatih/color` and in the end it's using in `Sprint` the `wrap` function. This is calling `unset`. If we're adding a second item to a color (e.g. bold and italic) it's just resetting one attribute. 

That's at least my understanding. You can try to remove one attribute. Personally I'd remove the `color.Italic` functionality anyway. :)
