### ISSUE TITLE
Termux build for Android?

### ISSUE THREAD

**Issue by afandian** [ultralist/ultralist#176]
Android has a full terminal environment and lots of popular packages have been compiled to run there. Any chance of getting a https://termux.com/ build?

**Comment by gammons** [comment]
@afandian I think this should "just work" by installing golang (see http://rafalgolarz.com/blog/2017/01/15/running_golang_on_android/) and running `go get -u github.com/ultralist/ultralist`.  

This did make me realize that I'm not currently building an arm-specific version of ultralist for releases currently.  I just added the arm build to the [current release](https://github.com/ultralist/ultralist/releases/tag/0.9.3).  let me know if that works for android / termux.

**Comment by gammons** [comment]
note, if you download the binary from the release page, then you don't need to install golang in termux.

**Comment by gammons** [comment]
closing for now.  re-open if there is an issue here.

**Comment by afandian** [comment]
The ARM binary build does work on Termux on Android! Amazing, thank you.

**Comment by afandian** [comment]
... almost. It segfaults, reported in #179
