### ISSUE TITLE
[bug] prioritized list items loose alignment (missing tab)

### ISSUE THREAD

**Issue by mahiki** [ultralist/ultralist#186]
When I prioritize any list item, the tab between the item id and the `[ ]` box disappears, pushing the list out of alignment.

```
 41	[ ]	          	+datasci @datasci-24: statistical learning class
 39	[ ]	          	+datasci troy hunt download pwned accounts, run 
 70[ ]	Sat Jan 20	+datasci @julia issue 99 coursera
 83	[ ]	Fri May 11	+top +datasci postgres mandelbrot repo issue
```

The prioritized items are BOLD, which is expected and good. Seems like a char gets swallowed somewere.

**Comment by gammons** [comment]
this should be fixed with the new screen printer.

**Comment by mahiki** [comment]
Thank you, huge improvement to UX!
