### ISSUE TITLE
 Cannot connect to api.ultralist.io right now.

### ISSUE THREAD

**Issue by talentlessguy** [ultralist/ultralist#187]
When I try to synchronize my todo list I get this:

```
~ 
❯ ultralist sync
Give this list a nametodos
Cannot connect to api.ultralist.io right now.
```

I tried with both my IP and using shadowsocks proxy (I thought that host is unreachable) but neither non-proxy nor proxy requests work.

OS: Manjaro Linux x64
Installed with: Golang

**Comment by gammons** [comment]
hey @talentlessguy I'm not able to repro on my end.  could be a network blip or something?  are you still having this problem?

**Comment by talentlessguy** [comment]
@gammons closing it. After reboot everything works nice, however, would be cool to output the stack trace or any warning to know what's wrong

**Comment by gammons** [comment]
yeah, the stack runs on heroku right now and I wouldn't say I have excellent logging/monitoring there.  That should change over time.
