### ISSUE TITLE
Change the name of or delete a synced list?

### ISSUE THREAD

**Issue by Benjamin-Lee** [ultralist/ultralist#190]
I can't quite figure out how to change the name of a synced list. I changed its name in `~/.config/ultralist/synced_lists.json` but am not seeing that reflected online. Similarly, I can't figure out how to delete a synced list and am not seeing it in the docs. Any pointers?

**Comment by gammons** [comment]
hey @Benjamin-Lee !  This might be a hole/gap with list syncing.  Can you let me know the list name and what you want to change it to?  I can just update it in the backend for now.

**Comment by gammons** [comment]
closing for now.  let me know the list name if you'd still like it fixed.

**Comment by jhollowed** [comment]
I'd also really appreciate this feature being implemented
