### ISSUE TITLE
[feature request] Ability to set task "status" or "stage"

### ISSUE THREAD

**Issue by sadmachine** [ultralist/ultralist#194]
Ultralist has really filled my needs in almost all ways except for the lack of a way to give tasks a status or a stage. For instance, even a simple "start" and "stop" function for tasks would be great. Example usage would be:

```
$ ultralist start 1
Todo 1 started.
$ ultralist list

all
1 [ ](Active)  . . .

$ ultralist stop 1
Todo 1 stopped.
$ ultralist list

all
1  [ ]          . . .
```

Also the edition of a way to modify the "status" or "stage" of a task manually with the edit command would be a really cool bonus feature, for instance:

```
$ ultralist edit 1 status Active
Todo 1 status Active.
$ ultralist edit 1 status Blocked
Todo 1 status Blocked
$ ultralist list

all
1 [ ](Blocked)   . . .
```

**Comment by gammons** [comment]
@sadmachine this is something I'll be implementing soon!

**Comment by gammons** [comment]
@sadmachine see #206 and let me know what you think.
