### ISSUE TITLE
Provision for recurrence example every monday

### ISSUE THREAD

**Issue by ersuniljoshi** [ultralist/ultralist#207]

**Comment by gammons** [comment]
@ersuniljoshi could you give an example of what you'd like to see?

**Comment by ersuniljoshi** [comment]
@gammons  I am coming from taskwarrior and uses it heavily.

Example: Send a status report to @bob every week on monday.
recur: weekly/monthly/bieekly/yearly/daily 

Not sure if I can reopen this
