### ISSUE TITLE
[Feature Request] Recurrence functionality

### ISSUE THREAD

**Issue by ersuniljoshi** [ultralist/ultralist#210]
#207  was closed, and I am not sure how to reopen it .
`
ultralist a Send a status report to @bob due:mon recur: weekly
`
Other values can be recur: weekly/monthly/bieekly/yearly/daily

**Comment by gammons** [comment]
we'll keep this issue open to talk through it.

@ersuniljoshi one challenge here is that it's hard to know when to create the next recurring task.  Should that happen when the previous one was marked completed?

**Comment by ersuniljoshi** [comment]
I need to check this how Taskwarrior handles this, it triggers when we show case our pending task. 
I can recall this when sometime i perform my task list command in taskwarrior, i got message like creating task .... 
and those are my recurring task itself.

**Comment by ersuniljoshi** [comment]
@gammons  I checked this and this happens exactly when I perform task list on a day. It performs a check with recurring task and create another task.

Let me know if you need more inputs from me.

**Comment by gammons** [comment]
FYI, I'm implementing this now :tada: in https://github.com/ultralist/ultralist/pull/233
