### ISSUE TITLE
Stale link

### ISSUE THREAD

**Issue by manfredlotz** [ultralist/ultralist#214]
At the bottom of https://ultralist.launchaco.com/ there is a link
    Docs: https://docs.ultralist.io/ which is stale,

**Comment by gammons** [comment]
Hi @manfredlotz nice catch!  although the main marketing site is at https://ultralist.io.  how did you end up on https://ultralist.launchaco.com/ ?

**Comment by manfredlotz** [comment]
Both https://ultralist.io, and https://ultralist.launchaco.com/ were shown when I googled.

**Comment by gammons** [comment]
Ended up finding my login for launchaco and deleted the site.  thanks again @manfredlotz

**Comment by manfredlotz** [comment]
You are welcome. :-)
