### ISSUE TITLE
Adding a new todo creates a .todos.json in current directory instead of adding it to global .todos.json

### ISSUE THREAD

**Issue by tcassaert** [ultralist/ultralist#219]
When I create a new todo, it creates by default a new .todos.json when there is none in the current directory. I expected it to add the new todo to the .todos.json in my home directory.

**Comment by gammons** [comment]
Hi @tcassaert this is by design.  [See the docs here](https://ultralist.io/docs/cli/managing_lists/#creating-a-todolist).

**Comment by tcassaert** [comment]
Maybe I've not explained the issue clear enough.

With the latest version, the current behavior is happening:

I have a `.todos.json` in my home directory. When I am in another directory, let's say in `/tmp` where there is no `.todo.json` file, and I add a new todo, there is a file created `/tmp/.todos.json`. 

According to the docs,  it should use the `.todos.json` in my home directory in this situation, and not create a new .todos.json file in /tmp.

**Comment by gammons** [comment]
ohhhh.  yeah.  that's an issue!

**Comment by gammons** [comment]
I replicated this.  thanks for finding it!

**Comment by gammons** [comment]
@tcassaert just published 1.5.1 which fixes this issue.  thanks again!

**Comment by mahiki** [comment]
Awesome, thanks for acting so quickly on this. I didn't notice this happening after upgrading to v1.2, ended up littering my folders wtih a few .todo.json files, but not hard to remediate.
