### ISSUE TITLE
Due dates don't seem to work

### ISSUE THREAD

**Issue by NileDaley** [ultralist/ultralist#221]
I recently updated ultralist to v1.5.1 ( from v1.1 ), and it seems like due dates now don't work.

As shown in the screenshot, I ran:

```sh
ultralist a +devops make @bob a sysadmin due tom
ultralist list
ultralist list due:tom
```

![Screenshot 2020-09-28 at 13 39 53](https://user-images.githubusercontent.com/15862011/94433833-c8294b80-0190-11eb-8616-ea08617c8835.png)

**Comment by NileDaley** [comment]
Apologies, running `ultralist add --help` showed that the dates should now be using `due:tom` format. 

I was looking at the [docs site](https://ultralist.io/docs/cli/managing_tasks/#adding-todos) which doesn't seem to have been updated yet

**Comment by gammons** [comment]
ah, thanks for finding that!  I'll get the docs updated today.

**Comment by gammons** [comment]
@NileDaley  I realized I had some redundant docs on the page.  Check out [showing tasks](https://ultralist.io/docs/cli/showing_tasks/) for detailed docs on listing.

**Comment by NileDaley** [comment]
I thought that might have been the case, once I'd seen the `--help` output from ultralist. The docs look good, and there's some solid examples 👍
