### ISSUE TITLE
Ordering by project using '+project'

### ISSUE THREAD

**Issue by tcassaert** [ultralist/ultralist#222]
In previous releases, there was an option to list tasks per project by using `ultralist list +project` but that doesn't work anymore. Is there a specific reason to have removed this type of filtering? I know there now is the `ultralist list project:project` but that's harder to type of course.

**Comment by gammons** [comment]
this was part of a larger rewrite of how filters work.  I'll look into supporting how it used to work.  You could always pipe into `grep` or `fzf`!

**Comment by tcassaert** [comment]
I've for now added a simple function:
```
function ull () {
  ultralist list project:"$1"
}
```
That keeps the original color output.

**Comment by gammons** [comment]
gonna close for now.
