### ISSUE TITLE
Could not parse the date you gave me: 'agenda'

### ISSUE THREAD

**Issue by aldosch** [ultralist/ultralist#223]
Hey beautiful people I'm new here.

I noticed agenda may have been broken here: https://github.com/ultralist/ultralist/pull/215#issuecomment-682484509

I'm not clever enough to know how to fix this and would greatly appreciate some help. I was following the Best Practice guide and noticed many of the [aliases](https://ultralist.io/docs/cli/best_practices/#shell-aliases-are-your-friend) such as `up` no longer work:

```
$ ultralist l due:agenda group:project
Could not parse the date you gave me: 'agenda'
```

**Comment by gammons** [comment]
Hi @aldosch this will be fixed with #226 .  I'll be cutting a release this weekend after adding a couple of other fixes.
