### ISSUE TITLE
Editing an item's project, does only change the subject, not the project itself

### ISSUE THREAD

**Issue by tcassaert** [ultralist/ultralist#230]
I have an item:
```
ultralist list project:homelab
1   [ ]                          +homelab Improve monitoring
```
Now, I want to move that to another project:
```
ultralist edit 1 +homelab-monitoring Improve monitoring
```
When I list the item then, with a filter for the new project, it doesn't show.
```
ultralist list project:homelab-monitoring
```
However, it's still listed when I filter for the `homelab` project:
```
ultralist list project:homelab
1   [ ]                          +homelab-monitoring Improve monitoring
```

If I go look in todos.json, I see that indeed only the subject has been changed, but not the project.

**Comment by gammons** [comment]
@tcassaert good catch!  I just submitted a PR that I believe fixes the issue.  I'll do a release later today.
