### ISSUE TITLE
another issue for a newbie!

### ISSUE THREAD

**Issue by rhaynes74** [ultralist/ultralist#237]
Hi folks, I can't seem to add a note to a task.

smatm0013:~:% ultralist l

all
1  [ ]  Wed Dec 02              Prepare financial report for the meeting with international scientific committee

ultralist add note 1 here is a note
Invalid id: 'an'

What I am doing wrong? 

Thanks!

**Comment by gammons** [comment]
Hi @rhaynes74 this is actually a bug in the current release, and was [just fixed](https://github.com/ultralist/ultralist/pull/234) on the main branch.  I'll do a release today so it includes this fix!

**Comment by rhaynes74** [comment]
Many thanks!

**Comment by gammons** [comment]
1.6.3 is out!  https://github.com/ultralist/ultralist/releases/tag/1.6.3
