### ISSUE TITLE
contents of notes

### ISSUE THREAD

**Issue by rhaynes74** [ultralist/ultralist#238]
Hi folks, the recent bug fixed now allows me to add notes to tasks - but not all notes:

ul add note 1 (x-devonthink-item://7D425B20-EB31-4589-ACBA-A71D4F22A99B)

throws an error: 

zsh: number expected

**Comment by gammons** [comment]
Hi @rhaynes74 yeah, that will happen sometimes if you're using special characters.  What you can do is use quotes:

`ul add note 1 "(x-devonthink-item://7D425B20-EB31-4589-ACBA-A71D4F22A99B)"`
