### ISSUE TITLE
deleting note error - related to previous bug? 

### ISSUE THREAD

**Issue by rhaynes74** [ultralist/ultralist#239]
Listing my tasks/notes gives:

ul l --notes

all
1    [ ]  Wed Dec 02              Prepare financial report for +DD25 for the meeting with international scientific committee
  0                                 here is a note

but then 

ul d n 1 0

gives:

Invalid id: 'dn'

**Comment by gammons** [comment]
Yes, I believe so.  I'm working on this fix right now.

**Comment by gammons** [comment]
@rhaynes74 I just merged this PR #241 which resolves this issue. 

I also took the time to do a significant rewrite of the usage docs within the CLI.  I'll be cutting a new release today, once I rebase in these changes to the recurrence PR (#223 ).

**Comment by rhaynes74** [comment]
Many thanks!

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by rhaynes74** [comment]
Thanks!!

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by gammons** [comment]
closed with 1.7.0 release
