### ISSUE TITLE
Requiring libc6 2.32. Ubuntu 20.04 LTS only has libc6 2.31

### ISSUE THREAD

**Issue by BastionInCzech** [ultralist/ultralist#243]
Looking for workarounds

**Comment by gammons** [comment]
Hi @BastionInCzech 

How did you install golang, and what version of golang are you using?

**Comment by BastionInCzech** [comment]
Should have specified. I am using precompiled binaries. 
Release 1.7.0
ultralistlinux_amd64

**Comment by gammons** [comment]
Hi @BastionInCzech I just re-built 1.7.0 using `CGO_ENABLED=0`, which appears to have fixed the issue.  I verified it in a docker container.

I re-uploaded the 1.7.0 binaries on the [release page](https://github.com/ultralist/ultralist/releases/tag/1.7.0).  Please download the same binary and let me know if it works.

**Comment by gammons** [comment]
gonna close for now.  please re-open if that binary didn't work!

**Comment by BastionInCzech** [comment]
It works. I hope replying won't reopen this. 
Thanks
