### ISSUE TITLE
Refactoring the command-line flags 

### ISSUE THREAD

**Issue by NonerKao** [ultralist/ultralist#75]
Currently, we parse the cmd arguments manually and arbitrarily, which makes enhancements such as #59 difficult or containing too much duplicated work.

While the official `flags` package treats cmd args good, it implements Unix convention rather than `todolist`'s sub-command style.  How about applying cmd packages such as `urfave/cli` or `fps13/cobra`? Or does this incur unnecessary complexity?

**Comment by stuartskelton** [comment]
I have a WIP,  for this in cobra see https://github.com/stuartskelton/todolist/tree/cobrav2.

The conversion is relatively pain free, thought in my v1 branch (the one I was teaching myself how to use cobra) I found a few pain points but they should be pretty easy to overcome.

**Comment by NonerKao** [comment]
Seems promising.  @gammons  What do you think about this idea?

**Comment by gammons** [comment]
@stuartskelton I apologize about neglecting this PR for basically forever.  Want to open a PR?
