### ISSUE TITLE
Add to to linux package managers

### ISSUE THREAD

**Issue by gammons** [ultralist/ultralist#77]
* apt for ubuntu
* pacman
* etc.

**Comment by NonerKao** [comment]
I myself use Archlinux, and the `todolist-git` package in AUR is now maintained by me.  We need a lot more users to vote for the package so that we can send this tool to the official repository.

**Comment by gammons** [comment]
Nice, that's great @NonerKao.  Yeah, I don't really know much about the process to get todolist into the main list.  I did it for homebrew though!

**Comment by NonerKao** [comment]
Getting a software into distributions' official repo is definitely a milestone.  How about calling for help on this goal?  I believe there are many users from different Linux distributions.

For now,   
* Ubuntu
* Debian
* Centos
* OpenSuSE
* *BSD
* etc.
are without official support.

**Comment by gammons** [comment]
We could definitely set up a PPA for ubuntu.  That would be great.  The only thing stopping me from doing this is I am entertaining the idea of renaming this project to something that's a bit more unique so it's easier to google ;)

**Comment by chrisallick** [comment]
Would love this. Does anyone have a binary for ubuntu 16 x64? Or, is there a way to install this without install golang?

**Comment by gammons** [comment]
@chrisallick you can get a binary on the [releases page](https://github.com/ultralist/ultralist/releases).
